name: GTλs Blog
description: My personal blog

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 40
baseurl: /
disqus_shortname: 'gtalolitablog'

# Details for the RSS feed generator
url:            'http://your-blog-url.example.com'
author:         'Handrés Povidaiko'
authorTwitter:  'gtalolita'
permalink:       pretty

exclude: ["LICENSE", "README.md"]

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
